#check for any duplicate and if any remove them

In [37]:
import pandas as pd

In [38]:
# import dataset
df = pd.read_excel("datasets/ccl.xlsx")

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [ ]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df = pd.read_excel("datasets/ccl.xlsx")

In [ ]:
fd = df.duplicated()

In [ ]:
fd

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df.duplicated().sum()

np.int64(0)

Step 2

In [ ]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [ ]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [ ]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [ ]:
# steps to make all numbers in the phone number column to be of same length and formate
# step1 - replace all the unwanted charcters to empty string("")

In [ ]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x : str(x))

In [ ]:
df['Phone_Number'] = df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [ ]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10])

### abc-def-ghij

#### apply() => Apply is a Pandas function which will apply specified functionality to each value of series

In [ ]:
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6               --
7     876-678-3469
8               --
9     123-545-5421
10              --
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18              --
19    876-678-3469
Name: Phone_Number, dtype: object

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,706-695-0392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
# address
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [ ]:
# address
df['Address'].str.split(',')

0                      [123 Shire Lane,  Shire]
1                         [93 West Main Street]
2                          [298 Drugs Driveway]
3     [980 Paper Avenue,  Pennsylvania,  18503]
4                            [123 Dragons Road]
5                            [768 City Parkway]
6                           [1209 South Street]
7                               [98 Clue Drive]
8                            [123 Middle Earth]
9                 [25th Main Street,  New York]
10                     [612 Shire Lane,  Shire]
11                       [2394 Hogwarts Avenue]
12                           [2039 Main Street]
13                           [343 City Parkway]
14                              [214 HR Avenue]
15                       [2395 Hogwarts Avenue]
16            [121 Paper Avenue,  Pennsylvania]
17                            [3498 Super Lane]
18                                        [N/a]
19               [910 Tatooine Road,  Tatooine]
Name: Address, dtype: object

In [ ]:
df['Address'].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [ ]:
# spliting address into 3 sep cols
df[['street_Addres','City','Pin_Code']] = df['Address'].str.split(',',expand=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_Addres,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,706-695-0392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [ ]:
df['Paying Customer']

0     Yes
1      No
2       N
3     Yes
4       Y
5     Yes
6      No
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15     No
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [ ]:
df['Paying Customer'].str.replace('yes','y')

0     Yes
1      No
2       N
3     Yes
4       Y
5     Yes
6      No
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15     No
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [ ]:
df['Paying Customer']=df['Paying Customer'].str.replace('yes','y')

In [ ]:
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')

In [ ]:
df['Paying Customer']

0     Yes
1       N
2       N
3     Yes
4       Y
5     Yes
6       N
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15      N
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: object

In [ ]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column',
       'street_Addres', 'City', 'Pin_Code'],
      dtype='object')

In [ ]:
df['DO_Not Contact']=df['Paying Customer'].str.replace('yes','y')
df['DO_Not Contact']=df['Paying Customer'].str.replace('No','N')

In [ ]:
df['DO_Not Contact']

0     Yes
1       N
2       N
3     Yes
4       Y
5     Yes
6       N
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15      N
16    Yes
17      Y
18    N/a
19    Yes
Name: DO_Not Contact, dtype: object

In [ ]:
# remove columns
df.drop(columns=['Not_Useful_Column','Address'],inplace=True)

In [ ]:
fullname = "virat,kholi"
fullname.split(',')

['virat', 'kholi']

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street_Addres,City,Pin_Code,DO_Not Contact
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None,Yes
1,1002,Abed,Nadir,123-643-9775,N,Yes,93 West Main Street,None,None,N
2,1003,Walter,/White,706-695-0392,N,NaN,298 Drugs Driveway,None,None,N
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503,Yes
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None,Y
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None,Yes
6,1007,Jeff,Winger,--,N,No,1209 South Street,None,None,N
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None,N
8,1009,Gandalf,NaN,--,Yes,NaN,123 Middle Earth,None,None,Yes
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None,Yes
10,1011,Samwise,Gamgee,--,Yes,No,612 Shire Lane,Shire,None,Yes
11,1012,Harry,...Potter,706-695-0392,Y,NaN,2394 Hogwarts Avenue,None,None,Y
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None,Yes
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None,Yes
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None,N
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None,N
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None,Yes
17,1018,Clark,Kent,706-695-0392,Y,NaN,3498 Super Lane,None,None,Y
18,1019,Creed,Braton,--,N/a,Yes,N/a,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None,Yes

### Dealing with null values

In [ ]:
df.replace('N/a','',inplace=True)
df.replace('NaN','',inplace=True)

In [ ]:
df.replace('--','',inplace=True)

In [ ]:
import numpy as np

# N/a , None = > null value
type('N/a')

str

In [ ]:
df.fillna('',inplace=True)

In [ ]:
for i in df.index:
   if df.loc[i,'Do_Not_Contact'] == "Y" or df.loc[i,'Phone_Number'] == "Y":
      df.drop(i,inplace=True)

In [ ]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street_Addres,City,Pin_Code,DO_Not Contact
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,,Yes
1,1002,Abed,Nadir,123-643-9775,N,Yes,93 West Main Street,,,N
2,1003,Walter,/White,706-695-0392,N,,298 Drugs Driveway,,,N
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,,,Y
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,,,Yes
6,1007,Jeff,Winger,,N,No,1209 South Street,,,N
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,,,N
8,1009,Gandalf,,,Yes,,123 Middle Earth,,,Yes
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,,Yes
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,,Yes
11,1012,Harry,...Potter,706-695-0392,Y,,2394 Hogwarts Avenue,,,Y
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,,,Yes
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,,,Yes
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,,,N
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,,N
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,,Yes
17,1018,Clark,Kent,706-695-0392,Y,,3498 Super Lane,,,Y
18,1019,Creed,Braton,,,Yes,,,,
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,,Yes

In [ ]:
df['Do_Not_Contact']

0      No
1     Yes
2
4      No
5     Yes
6      No
7      No
8
9      No
10     No
11
12      N
13     No
14     No
15      N
16     No
17
18    Yes
19      N
Name: Do_Not_Contact, dtype: object

In [ ]:
for i in df.index:
   if df.loc[i,'Do_Not_Contact'] == "Y" or df.loc[i,'Phone_Number'] == "Y":
      df.drop(i,inplace=True)

In [ ]:
df.reset_index(inplace=True,drop=True)

In [ ]:
df

In [ ]:
df.to_csv('Datasets\ccl2.xlsx',index=False)